# Generated by Django 2.0.7 on 2018-07-28 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OV', 'Overdue'), ('CL', 'Closed'), ('IP', 'In progress'), ('O', 'Open')], default='O', max_length=11)),
                ('supervisor', models.CharField(max_length=60)),
                ('other_participants', models.CharField(max_length=60)),
                ('ehhs', models.CharField(max_length=60)),
                ('manager', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='corrective_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='hsse_api.CorrectiveAction'),
            preserve_default=False,
        ),
    ]
