# Generated by Django 2.0.7 on 2018-07-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0002_auto_20180728_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorrectiveAction',
            new_name='Corrective_Action',
        ),
    ]
