# Generated by Django 2.0.7 on 2018-08-01 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0002_auto_20180801_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='site',
            name='employee_com_activity',
        ),
        migrations.RemoveField(
            model_name='site',
            name='environmental_indicator',
        ),
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='audit_inspection',
        ),
        migrations.RemoveField(
            model_name='user',
            name='corrective_action',
        ),
        migrations.RemoveField(
            model_name='user',
            name='report',
        ),
        migrations.AddField(
            model_name='audit_inspection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corrective_action',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_community_activity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
        ),
        migrations.AddField(
            model_name='environmental_indicators',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safety_activity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
        ),
    ]
