# Generated by Django 2.0.7 on 2018-08-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0004_auto_20180801_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contributing_actions',
            field=models.CharField(choices=[('ONT', 'Operating w/o necessary training'), ('FMS', 'Failure to make secure'), ('OUS', 'Operating at unsafe speed'), ('IWS', 'Inadequate warning/signal'), ('NSD', 'Nullified safety device'), ('UDE', 'Used defective equipment'), ('UEU', 'Used equipment unsafely'), ('UWE', 'Used wrong tool/equipment'), ('IGD', 'Inadequate guard/safety device'), ('HA', 'Hazardous attire'), ('FEH', 'Fire or explosion hazard'), ('UAM', 'Unsecured against movement'), ('PH', 'Poor housekeeping'), ('POH', 'Protruding object hazard')], max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='contributing_conditions',
            field=models.CharField(choices=[('IGD', 'Inadequate guard/safety device'), ('HA', 'Hazardous attire'), ('IWS', 'Inadequate warning/signal'), ('UAM', 'Unsecured against movement'), ('PH', 'Poor housekeeping'), ('POH', 'Protruding object hazard'), ('CCC', 'Close clearance/congestion'), ('HAS', 'Hazardous arrangement/storage'), ('DTE', 'Defective tools/equipment'), ('AC', 'Atmospheric condition'), ('INH', 'Illumination/noise hazard'), ('OUC', 'Other unsafe condition'), ('NUC', 'No Unsafe condition')], max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='influenced_actions',
            field=models.CharField(choices=[('UJH', 'Unaware of job hazards'), ('ITH', 'Inattention to hazard'), ('USM', 'Unaware of safe method'), ('LLJS', 'Low level job skill'), ('TGST', 'Tried to gain or save time'), ('TAEF', 'Tried to avoid extra effort'), ('TAD', 'Tried to avoid discomfort'), ('CBE', 'Caused by employee'), ('CAE', 'Caused by another employee'), ('DNU', 'Defective from normal use'), ('ISI', 'Inadequate safety inspection'), ('IHC', 'Inadequate housekeeping/clean-up'), ('FDC', 'Faulty desing/construction')], max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='influenced_conditions',
            field=models.CharField(choices=[('CBE', 'Caused by employee'), ('CAE', 'Caused by another employee'), ('DNU', 'Defective from normal use'), ('DAM', 'Defective via abuse/misuse'), ('ISI', 'Inadequate safety inspection'), ('IHC', 'Inadequate housekeeping/clean-up'), ('FDC', 'Faulty desing/construction'), ('OC', 'Outside contractor'), ('IPM', 'Inadequate preventive maintenance'), ('PP', 'Purchasing practice'), ('DE', 'Deteriorating exposure'), ('MA', 'Management acceptance'), ('OSC', 'Other source case'), ('USC', 'Unkwon source cause')], max_length=3),
        ),
    ]
