# Generated by Django 2.0.7 on 2018-08-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0005_auto_20180801_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='influenced_actions',
            field=models.CharField(choices=[('UJH', 'Unaware of job hazards'), ('ITH', 'Inattention to hazard'), ('USM', 'Unaware of safe method'), ('LLJS', 'Low level job skill'), ('TGST', 'Tried to gain or save time'), ('TAEF', 'Tried to avoid extra effort'), ('TAD', 'Tried to avoid discomfort'), ('CBE', 'Caused by employee'), ('CAE', 'Caused by another employee'), ('DNU', 'Defective from normal use'), ('ISI', 'Inadequate safety inspection'), ('IHC', 'Inadequate housekeeping/clean-up'), ('FDC', 'Faulty desing/construction')], max_length=4),
        ),
    ]
