# Generated by Django 2.0.7 on 2018-08-02 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0007_auto_20180802_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_inspection',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_community_activity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activity_sites', to='hsse_api.Site'),
        ),
        migrations.AlterField(
            model_name='employee_community_activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activity_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='environmental_indicators',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_sites', to='hsse_api.Site'),
        ),
        migrations.AlterField(
            model_name='safety_activity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sites', to='hsse_api.Site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sites', to='hsse_api.Site'),
        ),
    ]
