# Generated by Django 2.0.7 on 2018-08-02 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0008_auto_20180802_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_inspection',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corrective_action',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corrective_action',
            name='ehhs_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corrective_action',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_community_activity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activities', to='hsse_api.Site'),
        ),
        migrations.AlterField(
            model_name='employee_community_activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='environmental_indicators',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_indicators', to='hsse_api.Site'),
        ),
        migrations.AlterField(
            model_name='safety_activity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_activities', to='hsse_api.Site'),
        ),
    ]
