# Generated by Django 2.0.7 on 2018-08-05 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0011_auto_20180802_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmental_indicators',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
            preserve_default=False,
        ),
    ]
