# Generated by Django 2.0.7 on 2018-08-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0013_auto_20180805_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
        ),
    ]
