# Generated by Django 2.0.7 on 2018-08-05 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0014_auto_20180805_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_inspection',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_community_activity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsse_api.Site'),
        ),
        migrations.AlterField(
            model_name='employee_community_activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
