# Generated by Django 2.1 on 2018-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0015_auto_20180805_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body_part',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='body_side',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='case_type',
            field=models.CharField(choices=[('FA', 'First Aids'), ('MT', 'Medical Treatment'), ('RA', 'Restricted Activity'), ('LD', 'Lost Days'), ('IFE', 'Injury Free Event')], max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctor_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='exact_location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='local_clinic_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='type_injury',
            field=models.CharField(max_length=120),
        ),
    ]
