# Generated by Django 2.1 on 2018-08-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0016_auto_20180806_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit_inspection',
            old_name='made_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='employee_community_activity',
            old_name='user',
            new_name='created_by',
        ),
    ]
