# Generated by Django 2.1 on 2018-08-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0018_auto_20180816_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='apporved_date',
            new_name='approved_date',
        ),
    ]
