# Generated by Django 2.1 on 2018-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0022_auto_20180816_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
