# Generated by Django 2.1 on 2018-09-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0026_auto_20180817_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
    ]
