# Generated by Django 2.1 on 2018-10-13 15:59

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0027_remove_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalindicator',
            name='month_created',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentalindicator',
            name='year_created',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='month_created',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='year_created',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='month_created',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='year_created',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
