# Generated by Django 2.1 on 2018-11-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0032_auto_20181112_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditinspection',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AuditInspection',
        ),
    ]
