# Generated by Django 2.1 on 2018-11-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0033_auto_20181112_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(max_length=120),
        ),
    ]
