# Generated by Django 2.1 on 2018-11-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0034_auto_20181112_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecommunityactivity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeecommunityactivity',
            name='site',
        ),
        migrations.DeleteModel(
            name='EmployeeCommunityActivity',
        ),
    ]
