# Generated by Django 2.1 on 2018-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0035_auto_20181123_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contractor',
            field=models.BooleanField(),
        ),
    ]
