# Generated by Django 2.1 on 2018-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0036_auto_20181125_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contractor',
            field=models.BooleanField(default=False),
        ),
    ]
