# Generated by Django 2.1.3 on 2018-12-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsse_api', '0037_auto_20181125_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalindicator',
            old_name='waste_to_landfield',
            new_name='waste_to_landfill',
        ),
    ]
